// Generated by gencpp from file calculate_factorial/serverRequest.msg
// DO NOT EDIT!


#ifndef CALCULATE_FACTORIAL_MESSAGE_SERVERREQUEST_H
#define CALCULATE_FACTORIAL_MESSAGE_SERVERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace calculate_factorial
{
template <class ContainerAllocator>
struct serverRequest_
{
  typedef serverRequest_<ContainerAllocator> Type;

  serverRequest_()
    : number(0)  {
    }
  serverRequest_(const ContainerAllocator& _alloc)
    : number(0)  {
  (void)_alloc;
    }



   typedef int64_t _number_type;
  _number_type number;





  typedef boost::shared_ptr< ::calculate_factorial::serverRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::calculate_factorial::serverRequest_<ContainerAllocator> const> ConstPtr;

}; // struct serverRequest_

typedef ::calculate_factorial::serverRequest_<std::allocator<void> > serverRequest;

typedef boost::shared_ptr< ::calculate_factorial::serverRequest > serverRequestPtr;
typedef boost::shared_ptr< ::calculate_factorial::serverRequest const> serverRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::calculate_factorial::serverRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::calculate_factorial::serverRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace calculate_factorial

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::calculate_factorial::serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::calculate_factorial::serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calculate_factorial::serverRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::calculate_factorial::serverRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calculate_factorial::serverRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::calculate_factorial::serverRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::calculate_factorial::serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2a1b249ff0900a6eb941a743f359017a";
  }

  static const char* value(const ::calculate_factorial::serverRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2a1b249ff0900a6eULL;
  static const uint64_t static_value2 = 0xb941a743f359017aULL;
};

template<class ContainerAllocator>
struct DataType< ::calculate_factorial::serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "calculate_factorial/serverRequest";
  }

  static const char* value(const ::calculate_factorial::serverRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::calculate_factorial::serverRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 number\n\
";
  }

  static const char* value(const ::calculate_factorial::serverRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::calculate_factorial::serverRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.number);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serverRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::calculate_factorial::serverRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::calculate_factorial::serverRequest_<ContainerAllocator>& v)
  {
    s << indent << "number: ";
    Printer<int64_t>::stream(s, indent + "  ", v.number);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CALCULATE_FACTORIAL_MESSAGE_SERVERREQUEST_H
